name: Run Lint and Build

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]
    workflow_dispatch:

jobs:
    validate:
        name: Setup database, Lint, Type Check & Test
        runs-on: ubuntu-latest

        env:
            DATABASE_SCHEMAS: accounts
            DATABASE_URL: postgres://postgres:testPassword@localhost:5432/base_hono_testing
            NODE_ENV: test
            LIVE_TAIL_SOURCE_TOKEN: xxxxxxxxxxxxxxxxx
            JWT_SECRET: sometestsecret
            JWT_EXPIRY: 2d
            SENDGRID_API_KEY: SG.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            BREVO_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            MAILGUN_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxx
            MAILGUN_DOMAIN_NAME: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            DATABASE_HOST: 127.0.0.1
            DATABASE_NAME: base_hono_testing
            DATABASE_USER: postgres
            DATABASE_PASSWORD: testPassword

        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_USER: ${{ env.DATABASE_USER }}
                    POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Set up PostgreSQL Database
              run: |
                  sudo apt-get install postgresql-client
                  PGPASSWORD=${{ env.DATABASE_PASSWORD }} psql -h ${{ env.DATABASE_HOST }} -U ${{ env.DATABASE_USER }} -c 'CREATE DATABASE ${{ env.DATABASE_NAME }};'

            - name: ⎔ Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.1.34

            - name: ⬇️ Checkout to the sales api repo
              uses: actions/checkout@v4

            - name: 📥 Download deps
              run: bun install

            - name: Run migrations and seeds
              run: |
                  echo "Running database migrations..."
                  echo
                  make migrate-run
                  echo
                  echo "Database migrations completed..."
                  echo
                  echo "Running database seeds..."
                  make seed-run
                  echo
                  echo "Database seeds completed..."

            - name: Run Lint ⬣ , Type check 🔎  and Tests 🧪
              run: |
                  bun run lint &
                  bun run type:check &
                  wait
                  bun run test
